version: '3'
services:
    fuseki:
        image: stain/jena-fuseki
        volumes:
           - /data/fuseki:/fuseki
        user: root
        ports:
           - 8082:3030
        depends_on:
           - jena
        environment:
           - ADMIN_PASSWORD=pw123
        restart: always
    jena:
        image: stain/jena
        volumes:
          - /data/rdf:/rdf
    webvowl:
        image: ukparliament/webvowl:latest
        ports:
           - 8083:8080
        links:
           - fuseki
    webprotege:
        image: skyplabs/webprotege
        ports:
           - 8084:8080
        volumes:
           - /data/webprotege:/data/webprotege
        networks:
           - app-tier
        depends_on:
           - mongodb
        user: root
    mongodb:
         image: bitnami/mongodb:latest
         volumes:
           - /data/mongo:/data/db
         user: root
         ports:
           - 8085:27017
           - 8086:28017
         networks:
           - app-tier
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1454
    app-tier:
        driver: bridge
